### PR TITLE
Rename option proxyfmu and build with Docker

### PR DESCRIPTION
**Pull request by ljamt**
libcosim option fmuproxy is renamed to proxyfmu

Getting an error when linking in the `gcc9`-`proxyfmu=True`-[build](https://github.com/open-simulation-platform/cosim-cli/runs/3381610411?check_suite_focus=true) that I appreciate help on solving:
```
... /0.8.0/osp/testing/package/3123ab7ca3fc5a20c4e01288f8e98c00a155d3bd/lib/libcosim.so: undefined reference to `exp2@GLIBC_2.29'
... /0.8.0/osp/testing/package/3123ab7ca3fc5a20c4e01288f8e98c00a155d3bd/lib/libcosim.so: undefined reference to `log2@GLIBC_2.29'
```

### CODE REVIEW

**Comment by markaren** [comment]
https://github.com/open-simulation-platform/proxy-fmu/blob/54e161a5e3c2421d23aa3e16739958a432d4cf53/src/CMakeLists.txt#L72

Would it help if `dl` was not private? On deep water here.

**Comment by kyllingstad** [comment]
> Getting an error when linking in the `gcc9`-`proxyfmu=True`-[build](https://github.com/open-simulation-platform/cosim-cli/runs/3381610411?check_suite_focus=true) that I appreciate help on solving:
> 
> ```
> ... /0.8.0/osp/testing/package/3123ab7ca3fc5a20c4e01288f8e98c00a155d3bd/lib/libcosim.so: undefined reference to `exp2@GLIBC_2.29'
> ... /0.8.0/osp/testing/package/3123ab7ca3fc5a20c4e01288f8e98c00a155d3bd/lib/libcosim.so: undefined reference to `log2@GLIBC_2.29'
> ```

A quick guess is that this is caused by my changes to the CI build environment for libcosim. Probably, the glibc (C runtime library) version inside the Docker container is newer than the one on the base GitHub runners. A fix would be to change to a Docker-based solution for libcosimc too.

**Comment by kyllingstad** [comment]
To be a bit more explicit:

  * libcosim is _compiled_ against some glibc version inside a Docker container
  * ...but here it gets _run_ in an environment with an _older_ version of glibc

I haven't verified this, but we've had the same problem with GitHub's runners before. And the runner we're using here is ubuntu-18.04 which is itself a rather old OS by now.

**Comment by kyllingstad** [comment]
> A fix would be to change to a Docker-based solution for libcosimc too.

Sorry, I meant _cosim-cli_, not libcosimc.

**Comment by ljamt** [comment]
> > A fix would be to change to a Docker-based solution for libcosimc too.
> 
> Sorry, I meant _cosim-cli_, not libcosimc. But probably libcosimc too, come to think of it, though that's not the issue here.

Seems to be an issue for libcosimc as well: https://github.com/open-simulation-platform/libcosimc/actions/runs/1147215089

**Comment by ljamt** [comment]
Trying a docker-based build approach here as well. Works for gcc8 and gcc9, but having issues with gcc7.
@kyllingstad and @markaren, can you spot the problem? 
https://github.com/open-simulation-platform/cosim-cli/runs/3411263696?check_suite_focus=true

**Comment by markaren** [comment]
Seems it uses a old gcc7 version (7.2)? Default on Ubuntu 18.04 is gcc 7.5 (?)

**Comment by kyllingstad** [comment]
I'm not sure we need to build with all that many compiler versions, though, since cosim-cli is an executable and not a library. We're even bundling dependencies in the distributed packages, so we're not depending much on the user's environment.

**Comment by ljamt** [comment]
> Seems it uses a old gcc7 version (7.2)? Default on Ubuntu 18.04 is gcc 7.5 (?)

Currently using the conanio/gcc7 image, but I have tested with conanio/gcc72 with the same result. There's no other conanio image with gcc7 available.

**Comment by ljamt** [comment]
> I'm not sure we need to build with all that many compiler versions, though, since cosim-cli is an executable and not a library. We're even bundling dependencies in the distributed packages, so we're not depending much on the user's environment.

Removed the gcc7 build now

**Review by kyllingstad — APPROVED** [review]
Looks good!

**Pull request merged**
